### ISSUE TITLE
Broken link check step has trouble parsing some links

### ISSUE THREAD

**Issue by iamEAP** [run-crank/cog-inbox-mailgun#22]
## Repro Steps
1. Run the following scenario, using the `--debug` flag so that structured data is always printed.

```yml
scenario: Email Links Not Parsed
description: Run with --debug to show problem.

tokens:
  test.email: 96426f22-af1c-4f52-978e-9616002c24a6@thisisjust.atomatest.com

steps:
- step: Given I navigate to http://go.automatoninc.com/Dev-QA-Email-Confirmation.html
- step: And I fill out [name=FirstName] with Atoma
- step: And I fill out [name=LastName] with Tommy
- step: And I fill out [name=Email] with {{test.email}}
- step: "And I submit the form by clicking #mktoForm_1105 button[type=submit]"
- step: Then the 1st mailgun email for {{test.email}} should not contain broken links
  failAfter: 120
- step: Finally, delete the {{test.email}} marketo lead
```

**Expected**: The `Found Links` table (returned on the broken link check step) should contain a single URL.

**Actual**: The `Found Links` table is empty.

![Screen Shot 2020-03-26 at 6 13 01 PM](https://user-images.githubusercontent.com/3496491/77711219-9c34cf80-6f8d-11ea-8afb-b4cd54f1632e.png)
